discourse/discourse-subscriptions

- .rubocop.yml
- Gemfile.lock
- assets/javascripts/discourse/controllers/s-show.js.es6
- config/locales/client.en.yml
If a bad card number was entered and the subscribe button clicked, the
subscription button still disappeared and subscribing was not possible
without refreshing the page.
Also adds a missing tooltip too.
>  FIX: Loading state persists after bad card entered

- app/controllers/discourse_subscriptions/subscribe_controller.rb
- assets/javascripts/discourse/components/login-required.js.es6
- assets/javascripts/discourse/components/product-list.js.es6
- assets/javascripts/discourse/controllers/s-index.js.es6
- assets/javascripts/discourse/controllers/s-show.js.es6
- assets/javascripts/discourse/routes/s-show.js.es6
- assets/javascripts/discourse/templates/components/login-required.hbs
- assets/javascripts/discourse/templates/components/product-list.hbs
- assets/javascripts/discourse/templates/s/index.hbs
- assets/javascripts/discourse/templates/s/show.hbs
- config/locales/client.en.yml
- test/javascripts/helpers/product-pretender.js.es6
Previously we'd throw a 404 to anonymous users hitting the `/s/product_id` route, and not really give them anywhere to go on `/s`. This PR introduces a new flow:
- Browse to one of the pages
- Instead of being presented with a 404, see content now and instead get a login button
- Login writes the `destination_url` cookie to the current URL so that upon login, they're automatically redirected back
- PROFIT (literally)
I initially tried implementing this approach server-side only using the `redirect_to_login` method, it only stopped the model calls from the front end instead of directly redirecting to `/login`. I wasn't quite able to figure out this one. However, I think this is a better solution in the long run as it keeps the user in the checkout flow vs simply bouncing them to the login …
> FEATURE: Better UX for anonymous users

- assets/javascripts/discourse/templates/s/show.hbs
- assets/stylesheets/common/subscribe.scss
Due to putting the Stripe Elements HTML inside an if block in the
template, this caused state to be funky. As a result, calling
`this.stripe.createToken` failed to return a promise. Opted instead to
hide the elements via CSS for anonymous users to prevent this
showstopping bug.
> FIX: Payments could not complete

- assets/javascripts/discourse/controllers/admin-plugins-discourse-subscriptions-products-show-plans-show.js.es6
- assets/javascripts/discourse/routes/admin-plugins-discourse-subscriptions-products-show-plans-show.js.es6
- assets/javascripts/discourse/templates/admin/plugins-discourse-subscriptions-products-show-plans-show.hbs
Reported here: https://meta.discourse.org/t/subscriptions-group-shows-as-added-when-not-added-to-the-plan/169825
The group box was blank, but upon save, the very first group was selected. This is unexpected behavior for users.
Instead of this, I opted to use a no-group setting, which means users won't be added to a group when they subscribe if "no-group" is selected.
> FIX: Properly allow no group to be selected

- assets/javascripts/discourse/controllers/s-show.js.es6
- assets/javascripts/discourse/models/plan.js.es6
Moving `Ember.computed` constants to imports to ensure compatibility with future versions of Discourse.
> DEV: Transition from Ember constant to imports

- plugin.rb
Bumping the API gem to 5.29.0 and to the latest API version. This takes into account changes in the API over the last few months and also lays the groundwork for some other improvements to the plugin (namely promo codes).
Tests are passing, and a manual runthrough of the plugin yielded no issues too.
> DEV: Bump Stripe API gem to 5.29.0

- app/controllers/discourse_subscriptions/user/payments_controller.rb
Encountered a bug where some one time payments were not showing under User > Billing > Payments. This was due to a simple error in the logic (and return syntax :man_facepalming: )
> FIX: Properly show one time payments in user billing

- app/controllers/discourse_subscriptions/subscribe_controller.rb
- assets/javascripts/discourse/controllers/s-show.js.es6
- assets/javascripts/discourse/models/subscription.js.es6
- assets/javascripts/discourse/models/user-subscription.js.es6
- assets/javascripts/discourse/templates/s/show.hbs
- assets/javascripts/discourse/templates/user/billing/subscriptions.hbs
- config/locales/client.en.yml
- spec/requests/subscribe_controller_spec.rb
This adds support for Stripe Promo Codes in the user checkout process. 
Also adds a discounted field to User > Billing > Subscriptions to show the amount or percent discounted.
This does not currently add in support for creating promo codes in the Subscriptions interface (that will come at a later point in time). Instead a coupon can be created with a promo code right from the Stripe dashboard.
> FEATURE: Support for coupons in checkout

- app/controllers/discourse_subscriptions/admin/coupons_controller.rb
- assets/javascripts/discourse/components/create-coupon-form.js.es6
- assets/javascripts/discourse/controllers/admin-plugins-discourse-subscriptions-coupons-index.js.es6
- assets/javascripts/discourse/controllers/admin-plugins-discourse-subscriptions-coupons.js.es6
- assets/javascripts/discourse/discourse-subscriptions-route-map.js.es6
- assets/javascripts/discourse/models/admin-coupon.js.es6
- assets/javascripts/discourse/routes/admin-plugins-discourse-subscriptions-coupons.js.es6
- assets/javascripts/discourse/templates/admin/plugins-discourse-subscriptions-coupons.hbs
- assets/javascripts/discourse/templates/admin/plugins-discourse-subscriptions.hbs
- assets/javascripts/discourse/templates/components/create-coupon-form.hbs
- assets/stylesheets/common/main.scss
- config/locales/client.en.yml
- config/routes.rb
- plugin.rb
- spec/requests/admin/coupons_controller_spec.rb
Adds full support to create coupon/promo codes in the Admin > Plugins > Subscriptions section of the plugin. The Create Coupon button opens a form on the same page, and the active checkboxes toggle the active status of the coupon code.
The Rails API is pretty simple so tests are light as otherwise we'd just be testing the Stripe mocking :)
> FEATURE: Allow creation of coupons in admin panel

- app/controllers/discourse_subscriptions/admin/products_controller.rb
- app/controllers/discourse_subscriptions/subscribe_controller.rb
- assets/javascripts/discourse/components/product-item.js.es6
- assets/javascripts/discourse/controllers/s-show.js.es6
- assets/javascripts/discourse/templates/admin/plugins-discourse-subscriptions-products-show.hbs
- assets/javascripts/discourse/templates/components/product-item.hbs
- assets/javascripts/discourse/templates/components/product-list.hbs
- assets/javascripts/discourse/templates/s/show.hbs
- config/locales/client.en.yml
- spec/requests/admin/products_controller_spec.rb
- spec/requests/subscribe_controller_spec.rb
Feature requested here: https://meta.discourse.org/t/subscriptions-allow-users-to-purchase-one-time-products-multiple-times/173732/
There may be cases where a site admin wants to allow the repurchasing of a product. This implements the functionality by adding a repurchaseable toggle in the admin screen when creating a product. This saves an attribute to the Stripe product metadata.
When a user has already purchased an item with this toggle enabled, they will be able to purchase it again when browsing to `/s`.
> FEATURE: Give option to repurchase products multiple times

- app/controllers/discourse_subscriptions/admin/subscriptions_controller.rb
- assets/javascripts/discourse/controllers/admin-plugins-discourse-subscriptions-subscriptions.js.es6
- assets/javascripts/discourse/models/admin-subscription.js.es6
- assets/javascripts/discourse/templates/admin/plugins-discourse-subscriptions-subscriptions.hbs
- spec/requests/admin/subscriptions_controller_spec.rb
Meta topic: https://meta.discourse.org/t/subscriptions-add-pagination-to-admin-subscriptions-view/172500
This adds support for pagination using our `{{load-more}}` component in core. Implementation on the backend was a bit tricky because we don't return all results from Stripe, only those that match local subscriptions stored in the `DiscourseSubscriptions::Subscription` model.
> FEATURE: Admin > Subscriptions Pagination

- assets/javascripts/discourse/templates/components/product-item.hbs
- assets/stylesheets/common/layout.scss
- config/locales/client.en.yml
﻿﻿<img width="811" alt="image" src="https://user-images.githubusercontent.com/11862022/107985735-42b40580-6f90-11eb-983e-7174f983fd75.png">
Suggested here: https://meta.discourse.org/t/subscriptions-suggestions-for-interface-improvements/177970
Changes order and alignment so it makes a bit more sense in the UX of the `/s` route. Otherwise it looks too cluttered. This specifically impacted products that can be repurchased.
> UX: Adjust repurchase styles to look better

- assets/stylesheets/common/main.scss
Reported here: https://meta.discourse.org/t/subscriptions-desc-style-overrides-user-cards/177478
This selector wasn't even used anywhere in the plugin but overrides styles in core.
> DEV: Remove unused CSS selector

- assets/javascripts/discourse/components/payment-options.js.es6
- assets/javascripts/discourse/helpers/format-currency.js.es6
- assets/javascripts/discourse/templates/components/payment-options.hbs
- assets/stylesheets/common/subscribe.scss
- test/javascripts/components/payment-plan-test.js.es6
PR does three things:
1. Remove the duplicative currency abbreviation in favor of the currency symbol alone
2. Reorders plans by the cost in ascending order.
3. Fixes a flexbox button bug
This makes the subscriptions page a bit cleaner.
> UX: Improve usability of purchase page

- lib/tasks/subscriptions.rake
`list` method in Stripe API defaults to  limit of 10 records only
this change should get all Products and Subscriptions from the Stripe account
> allow more than 10 of Stripe records

- assets/javascripts/discourse/connectors/above-main-container/subscriptions-campaign.js.es6
- assets/javascripts/discourse/connectors/before-topic-list/subscriptions-campaign-sidebar.js.es6
- assets/javascripts/discourse/templates/connectors/above-main-container/subscriptions-campaign.hbs
- assets/javascripts/discourse/templates/connectors/before-topic-list/subscriptions-campaign-sidebar.hbs
- assets/stylesheets/common/layout.scss
- assets/stylesheets/common/subscribe.scss
PR does two things:
These are pretty simple changes. The buttons were crammed together and not wrapping properly on mobile if there were more than a few. Also the padding was weird and causing text to overflow out of the `#main-outlet` on phone viewports.
In the original PR, we refactored using the connector JS out since we now have more Ember operators; however, we needed some more complex logic that couldn't be done in the template. Basically, we choose which outlet to render the component in based on two criteria:
1. If the setting is set to sidebar or top
2. If we're on a mobile device
Previously, if the site showed the banner on the sidebar and the user browsed to mobile, they wouldn't see a banner at all. This PR changes the logic to use the top outlet on mobile, even if the sidebar …
> UX: Improve mobile campaign flow

- config/routes.rb
- spec/requests/admin/coupons_controller_spec.rb
- spec/requests/admin/plans_controller_spec.rb
- spec/requests/admin/products_controller_spec.rb
- spec/requests/admin/subscriptions_controller_spec.rb
As reported [on Meta](https://meta.discourse.org/t/discourse-subscriptions/140818/352?u=justin), moderators could access all of the subscriptions data (plugins/prices/subscribers) and manage them. This should not be the case, so this PR adds a route constraint to 404 moderators from these routes.
> FIX: Restrict mods from seeing Subscriptions admin features

- app/controllers/discourse_subscriptions/subscribe_controller.rb
- assets/javascripts/discourse/controllers/s-show.js.es6
- config/locales/client.en.yml
- spec/requests/subscribe_controller_spec.rb
As reported on [Meta](https://meta.discourse.org/t/validate-coupon-codes/193181/), we weren't validating coupon codes on form submission, so an incorrect code could be used and no feedback was given to the end user. This PR fixes that up.
> FEATURE: Validate coupon codes on form submit

- assets/javascripts/discourse/components/campaign-banner.js.es6
- assets/javascripts/discourse/templates/components/campaign-banner.hbs
- config/locales/client.en.yml
- config/settings.yml
This PR adds the ability to use an uploaded image in the plugin settings as the background for the campaign banner.
> FEATURE: Add ability to use custom background image

- assets/javascripts/discourse/templates/components/campaign-banner.hbs
I think the Subscriber option should be `html-safe` like the Amount option otherwise you get this rendered in the browser:
> fix strong

- assets/javascripts/discourse/components/campaign-banner.js.es6
Very simple change here -- don't run the `/s/contributors` AJAX call unless the user is currently logged in. On `login_required` sites, allowing this call to run has a number of weird side-effects, including setting the `destination_url` cookie to `/s/contributors`. 
Instead, since we don't show the banner to anonymous users, we only need to allow this call when the user is currently logged in.
> FIX: New user sessions redirected weirdly on login_required sites

- app/services/discourse_subscriptions/campaign.rb
- assets/javascripts/discourse/components/campaign-banner.js.es6
- config/settings.yml
- plugin.rb
- spec/serializers/site_serializer_spec.rb
- spec/services/campaign_spec.rb
To avoid banner fatigue with the campaigns feature, the plugin should hide the banner after the goal is completed. However, we also want the banner to show up if the goal dips below a certain percentage.
This PR adds this functionality based on two states:
- If we've met the goal, hide banner after 7 days.
- If we've dipped below 90% of goal (after the goal is met), show the banner again.
Implementation-wise, the calculation on the goal being met happens when the campaign update job runs every 30 minutes. We're storing the details in two new site settings (`_campaign_goal_met`, `_campaign_goal_met_date`), which are then used by the client to determine if the banner should be shown/hidden. 
Essentially, if the `_campaign_goal_met_date` setting is set, the client calculates if we're 7 days …
> FEATURE: Show/hide campaign banner with goal status

- app/controllers/discourse_subscriptions/admin/plans_controller.rb
- spec/requests/admin/plans_controller_spec.rb
The interval field was missing in the Ember object since it was only available inside the nested object.
> FIX: set interval field correctly in object root for recurring plans.

- app/controllers/discourse_subscriptions/admin/plans_controller.rb
`.dig` isn't valid for stripe objects. This commit fixes this 500 error
you get when trying to edit a pricing plan:
```
NoMethodError (undefined method `dig' for #<Stripe::Price:0x....)
```
> FIX: 500 error when editing a pricing plan

- app/services/discourse_subscriptions/campaign.rb
- spec/services/campaign_spec.rb
On the subscription banner that shows on the top of the forum it shows
the total amount raised toward a goal. But the amount shown was not
including one-time purchases. It was only showing subscriptions.
This change updates the sync with stripe logic so that it also includes
one-time purchases.
See: https://meta.discourse.org/t/-/209591
> FIX: Include one-time purchases in campaign total

- app/services/discourse_subscriptions/campaign.rb
- spec/services/campaign_spec.rb
The campaign total should only include payments that have succeeded.
See: https://meta.discourse.org/t/209591/14
> FIX: Exclude blocked charges in campaign total

- assets/javascripts/discourse/templates/components/campaign-banner.hbs
We need to use the `html-safe` helper here so to that the html tags in
the translation template are rendered correctly.
See: https://meta.discourse.org/t/211376
> FIX: html strong tags showing

- app/controllers/discourse_subscriptions/user/payments_controller.rb
- spec/requests/user/payments_controller_spec.rb
Duplicate payments were showing up in the discourse ui for users. Actual
transactions in stripe were not being duplicated. This fix ensures that
when parsing the api response we don't append any duplicates. Added a
duplicate entry to the specs to test for this.
I do think there can be some improvements made to this controller
endpoint, but I'd like to save those for a different and larger PR and
just get this fix out first.
> FIX: Duplicate payments showing up in discourse UI

- lib/tasks/subscriptions_import.rake
The import script has a prompt asking if this is a "procourse" import or
not, but the logic for handling the answer is backwards and will
incorrectly set the `procourse_import` flag to `true`.
This commit also fixes a minor typo.
> FIX: Import script confirmation flag logic

- assets/javascripts/discourse/initializers/setup-subscriptions.js
This commit adds a "billing" button to the user profile dropdown menu.
> FEATURE: Add quick access button to user profile dropdown 

- spec/requests/admin/coupons_controller_spec.rb
- spec/requests/admin/plans_controller_spec.rb
- spec/requests/admin/subscriptions_controller_spec.rb
- spec/requests/subscribe_controller_spec.rb
It now supports strict keyword argument matching by default.
> DEV: Fix mocha deprecations

- assets/javascripts/discourse/routes/subscribe-index.js
- test/javascripts/acceptance/subscribe-test.js
At the moment, paying for a product typically involves first clicking the subscribe link added to the navigation bar, selecting a product and then adding card details to to make the purchase.
This change skips the product selection step if the site has only one product.
> FEATURE: Skip product listing if only one product is present

- assets/stylesheets/common/campaign.scss
Sample warning was:
```
Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.
Recommendation: math.div($sidebar-height, 1.2) or calc($sidebar-height / 1.2)
More info and automated migrator: https://sass-lang.com/d/slash-div
```
> DEV: Fixes SCSS deprecation in console

- assets/stylesheets/common/campaign.scss
Followup to https://github.com/discourse/discourse-subscriptions/pull/171
Also fixes:
```
╷
581 │       hsl(random(360), 100, 50);
│       ^^^^^^^^^^^^^^^^^^^^^^^^^
╵
/Users/pmusaraj/Projects/discourse/discourse-subscriptions.scss 581:7  root stylesheet
Deprecation Warning: $lightness: Passing a number without unit % (50) is deprecated.
```
> DEV: Fix SCSS deprecations

- config/locales/client.en.yml
- config/settings.yml
This is so the plugins settings are better categorized in the site settings UI.
> DEV: Change settings root from plugins: to discourse_subscriptions

- assets/javascripts/discourse/templates/admin/plugins-discourse-subscriptions-products-index.hbs
- spec/fabricators/customer_fabricator.rb
- spec/fabricators/product_fabricator.rb
- spec/system/page_objects/admin_subscription_product.rb
- spec/system/subscription_product_spec.rb
Regression from https://github.com/discourse/discourse-subscriptions/pull/158, where we were passing in `"product"` instead of `{{product}}`.
This commit ensures that the `product` item is passed in when deleting the product.
> FIX: Ensure deletion of product upon confirmation

- config/locales/client.en.yml
- test/javascripts/acceptance/subscribe-test.js
Turns out in YAML `NO` is interpreted as a boolean value, so we need to
wrap it in quotes.
> FIX: Translation missing for Norway

- app/serializers/discourse_subscriptions/payment_serializer.rb
- assets/javascripts/discourse/controllers/admin-plugins-discourse-subscriptions-products-show-plans-show.js
- assets/javascripts/discourse/helpers/format-currency.js
- config/settings.yml
It adds support for the ZAR currency (the official currency of South Africa)
> FEATURE: add ZAR currency support

- assets/javascripts/discourse/templates/user/billing/subscriptions/card.hbs
The save button for a user to update their cc was missing.
Looks like we can't override the computed property `savingText`. This
was causing the form to break. Likely was a change in core sometime ago.
> FIX: Update cc save button missing

- assets/javascripts/discourse/templates/admin/plugins-discourse-subscriptions.hbs
The Auto-Create Support Campaign button was just showing an infinite "is
loading" spinner so you couldn't even click on it.
This fix allows the button to work again and only show the loading
spinner when it is actually loading.
See: https://meta.discourse.org/t/discourse-subscriptions/140818/653?u=blake
> FIX: Auto-Create Support Campaign button

- app/controllers/discourse_subscriptions/admin/subscriptions_controller.rb
- app/controllers/discourse_subscriptions/hooks_controller.rb
- app/controllers/discourse_subscriptions/subscribe_controller.rb
- app/controllers/discourse_subscriptions/user/subscriptions_controller.rb
- db/migrate/20240430163338_add_status_to_subscriptions.rb
- spec/fixtures/json/stripe-price-list.json
- spec/fixtures/json/stripe-subscription-list.json
- spec/requests/admin/subscriptions_controller_spec.rb
- spec/requests/hooks_controller_spec.rb
- spec/requests/subscribe_controller_spec.rb
- spec/requests/user/subscriptions_controller_spec.rb
- spec/system/page_objects/admin_subscription_subscription.rb
- spec/system/page_objects/user_billing_subscription.rb
- spec/system/pricing_table_spec.rb
- spec/system/subscription_subscription_spec.rb
Instead of deleting customers on cancel we will now update the
subscription status to canceled. This way we can have some visibility on
which users have canceled.
> DEV: Stop deleting customers on cancel

- app/controllers/discourse_subscriptions/user/subscriptions_controller.rb
- spec/system/subscription_subscription_spec.rb
Users can have multiple customer records in our db, so we need to filter
out non-unique stripe customer ids before fetching subscriptions for each.
> FIX: Prevent duplicate stripe subscription list requests

- app/controllers/discourse_subscriptions/hooks_controller.rb
- assets/javascripts/discourse/templates/subscriptions.hbs
- spec/requests/hooks_controller_spec.rb
- spec/system/pricing_table_spec.rb
If an anonymous user tries to subscribe we need to show them a log in
message first. We currently don't have support for anonymous
subscriptions.
Follow up to: 45754baa0070f1fe600f4fd71d2d46e61d359b13
> FIX: Login required for Stripe Checkout

- app/controllers/discourse_subscriptions/subscribe_controller.rb
- app/controllers/discourse_subscriptions/user/payments_controller.rb
- spec/requests/subscribe_controller_spec.rb
This change ensures we attach the invoice item to the invoice to avoid
any occurrences of an empty invoice being paid with pending invoice
items.
> FIX: One-time purchase pending invoice item

- assets/javascripts/discourse/components/campaign-banner.hbs
- assets/javascripts/discourse/components/campaign-banner.js
- spec/system/pricing_table_spec.rb
If the new pricing table is enabled the campaign banner should link to
the pricing table route.
> FIX: Campaign banner should link to pricing table when enabled

- config/locales/client.en.yml
I am trying to enable `i18n.raise_on_missing_translations` in core. It caught a missing translation in this plugin.
> FIX: Add missing transaction error translation

- app/controllers/discourse_subscriptions/admin/subscriptions_controller.rb
- assets/javascripts/discourse/components/modal/admin-cancel-subscription.gjs
- assets/javascripts/discourse/controllers/admin-plugins-discourse-subscriptions-subscriptions.js
- spec/requests/admin/subscriptions_controller_spec.rb
Stripe at some point deprecated their `.delete` method on Subscription
in favor of `.cancel`. When we upgraded to latest stripe gem in dcde03d7c46661e447c22524ab376c95698b7517
this call likely stopped working.
In addition to this fix we are no longer deleting the customer record,
but instead of updating the status of it. This way an admin can easily
see 'active' as well as 'canceled' subscriptions. This behavior matches
what we are already doing for an individual user listing all of their
subscriptions.
Bug report: https://meta.discourse.org/t/316007
> FIX: Admins unable to cancel a subscription for a user

- app/services/discourse_subscriptions/campaign.rb
- spec/services/campaign_spec.rb
Depending on the invoices in stripe there could be some nil values for
things so we need to account for those in this job or an exception will
be thrown causing the job to fail.
> FIX: Exception with campaign refresh data job

- assets/javascripts/discourse/helpers/format-currency.js
- test/javascripts/helpers/format-currency-test.js
Amounts like $45.80 were being displayed as $45.8. Which doesn't look
correct for currency.
Bug Report: https://meta.discourse.org/t/316007
> FIX: Decimal point truncation

- app/controllers/discourse_subscriptions/hooks_controller.rb
- app/controllers/discourse_subscriptions/user/payments_controller.rb
- spec/requests/hooks_controller_spec.rb
- spec/requests/user/payments_controller_spec.rb
When using the Stripe Pricing table for one-off purchases
(non-subscriptions) the webhook was encountering an error because it was
expecting subscription information which does not exist for one-off
purchases. This fix addresses that issue ensuring that no errors occur,
that users are added to the appropriate group, and that uses can see
their purchase on the billing page.
> FIX: Pricing table for one-off purchases

- app/controllers/discourse_subscriptions/hooks_controller.rb
Follow up to: e92dd399280b0170e118e126464b7f3051c953a6
> DEV: Use warn instead of info for Rails logger

- app/controllers/discourse_subscriptions/hooks_controller.rb
- spec/requests/hooks_controller_spec.rb
When using the Stripe Pricing Table for one-off purchases
(non-subscription) stripe doesn't automatically create a customer
record. This was causing the pricing table webhook
endpoint to end prematurely and not add users to their appropriate
group after purchase. Now if we detect that there is no customer record
we will make an api call to Stripe to create one.
> FIX: Create customer for one off pricing table purchases

- app/controllers/discourse_subscriptions/hooks_controller.rb
- app/controllers/discourse_subscriptions/user/payments_controller.rb
- spec/requests/hooks_controller_spec.rb
Pricing table payments for one off purchases need to be attached to the
customer or they don't show up on the user's billing payments page.
> FIX: Payments not showing up for users

- app/controllers/discourse_subscriptions/hooks_controller.rb
- app/controllers/discourse_subscriptions/user/payments_controller.rb
- spec/requests/hooks_controller_spec.rb
- spec/requests/user/payments_controller_spec.rb
This change partly reverts 700c5e772743dc8c1f648ad8b6bf42018ef938cb
because of this Stripe error:
> Unexpected error: Some of the parameters you provided (customer) cannot be used when modifying a PaymentIntent that was created by Checkout. You can try again without those parameters.
Apparently we can't use PaymentIntent api for our use case. This commit
provides a work around there where we instead fetch the guest payments
if the pricing table is being used so that they show up on the user's
billing payments page.
> DEV: Fetch related guest payments

- assets/javascripts/discourse/routes/subscribe.js
- assets/javascripts/discourse/routes/subscriptions.js
- spec/system/pricing_table_spec.rb
If the pricing table is enabled the `/s` route should redirect to the
pricing table route and vice versa.
> FIX: Redirect to the pricing table page when enabled

- app/controllers/discourse_subscriptions/hooks_controller.rb
Sometimes users aren't added to groups so adding some more logging
statements to aid in debugging.
> DEV: Add some more verbose logging for debugging groups

- app/serializers/discourse_subscriptions/payment_serializer.rb
- assets/javascripts/discourse/controllers/admin-plugins-discourse-subscriptions-products-show-plans-show.js
- assets/javascripts/discourse/helpers/format-currency.js
- config/settings.yml
Stripe supports the Swiss Franc so we can add support for it.
https://meta.discourse.org/t/316003
> FEATURE: Add support for CHF currency

- assets/javascripts/discourse/components/campaign-banner.hbs
- assets/javascripts/discourse/components/create-coupon-form.hbs
- assets/javascripts/discourse/components/modal/admin-cancel-subscription.gjs
- assets/javascripts/discourse/templates/admin/plugins-discourse-subscriptions-coupons.hbs
- assets/javascripts/discourse/templates/admin/plugins-discourse-subscriptions-plans-index.hbs
- assets/javascripts/discourse/templates/admin/plugins-discourse-subscriptions-products-index.hbs
- assets/javascripts/discourse/templates/admin/plugins-discourse-subscriptions-products-show.hbs
- assets/javascripts/discourse/templates/admin/plugins-discourse-subscriptions-subscriptions.hbs
- assets/javascripts/discourse/templates/admin/plugins-discourse-subscriptions.hbs
- assets/javascripts/discourse/templates/user/billing/subscriptions/index.hbs
This PR updates more deprecated Font Awesome icon names. For more detail, refer to the announcement at https://meta.discourse.org/t/-/325349.
> DEV: Update more deprecated Font Awesome icon names

- app/services/discourse_subscriptions/campaign.rb
Mitigates `Deprecation notice: The icon name "donate" has been updated to "circle-dollar-to-slot". Please use the new name in your code. Old names will be removed in Q2 2025. [deprecation id: discourse.fontawesome-6-upgrade] [info: https://meta.discourse.org/t/325349]` message.
> FIX: FontAwesome 6 compatibility icon upgrade

- assets/stylesheets/common/campaign.scss
This PR makes a few styling tweaks to the campaign banner:
* Increases breakpoint at which the banner layout stacks into a column
* Remove styling when banner is in topic footer for consistency between placement
* Stack banner underneath topic footer buttons when on mobile
https://github.com/user-attachments/assets/167b3d71-8a2d-495e-b574-8be1f617d9b5
https://github.com/user-attachments/assets/3e14cf3b-ccdc-4391-8cf9-825c8a4d2062
> UX: Campaign banner layout improvements

- assets/stylesheets/common/campaign.scss
This PR ensures the campaign banner in the topic footer resizes correctly when the sidebar is present.
https://github.com/user-attachments/assets/5c584c12-a0c0-46ec-aa56-7b9f5aa21e91
https://github.com/user-attachments/assets/e36ad5a4-2cc2-4102-bc93-93f3a08e1c2a
> FIX: Campaign banner size when sidebar is active
